services:
  dash_app:
    build: .
    ports:
      - "8050:8050"
    environment:
      HOST: "192.168.100.49"
      PORT: "8050"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    